[package]
name = "hull"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
cargo_metadata = "0.5"
duct = "0.10"
shell-words = "0.1"
structopt = "0.2"
structopt-derive = "0.2"

[[bin]]
path = "src/main.rs"
name = "hull"
